version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:2.2
    container_name: jaeger
    ports:
      - "5775:5775/udp"       # UDP port for tchannel
      - "6831:6831/udp"       # UDP port for receiving spans
      - "6832:6832/udp"       # UDP port for sending spans
      - "5778:5778"           # HTTP port for sampling strategies
      - "16686:16686"         # HTTP UI port
      - "14268:14268"         # HTTP port for span data
      - "14250:14250"         # GRPC port
      - "9411:9411"           # HTTP port for Zipkin
    environment:
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_KEY=/badger/data
      - BADGER_DIRECTORY_VALUE=/badger/data
    volumes:
      - jaeger-data:/badger/data
    restart: always

volumes:
  jaeger-data:
    driver: local
